[package]
name = "ferris_ffi_plugin"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
crate-type = ["cdylib"]

[dependencies]
allo-isolate = { version = "^0.1", features = ["catch-unwind"] }

[build-dependencies]
cbindgen = "0.24.3"
