[config]
min_version = "0.35.0"

[env]
CARGO_MAKE_RUST_CHANNEL = "stable"
CARGO_MAKE_CRATE_WORKSPACE_MEMBERS = ["."]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
PLUGIN_NAME = "ferris_ffi_plugin"

[tasks.test-rust]
description = "Run rust tests"
command = "cargo"
args = ["test"]

[tasks.build-rust]
description = "Build rust plugin"
command = "cargo"
args = ["build", "--release"]

[tasks.copy-lib-to-macos]
description = "Copy rust plugin to macos folder"
command = "cp"
args = ["target/release/lib${PLUGIN_NAME}.dylib", "../macos"]

[tasks.clean-rust]
description = "Clean rust plugin"
command = "cargo"
args = ["clean"]

[tasks.ffigen]
description = "Run ffigen"
command = "flutter"
args = ["pub", "run", "ffigen", "--config", "ffigen.yaml"]
cwd = ".."

[tasks.clean-flutter]
description = "Clean flutter and get packages"
script = [
'''
flutter clean && flutter pub get && cd example && flutter clean && flutter pub get && cd ..
'''
]
cwd = ".."

[tasks.all]
description = "Run all tasks"
dependencies = [
    "test-rust",
    "build-rust",
    "copy-lib-to-macos",
    "clean-rust",
    "ffigen",
    "clean-flutter",
]
